### ISSUE TITLE
safari ui issue - leaves a mark when sliding

### ISSUE THREAD

**Issue by medinarodel** [angular-slider/ng5-slider#161]
<img width="590" alt="ng5-slider-issue" src="https://user-images.githubusercontent.com/294787/69960545-b2350500-1544-11ea-854a-f27a351dac89.png">

Works fine with Chrome & FF. Safari version tested against: Version 13.0.3 (15608.3.10.1.4)

**Comment by medinarodel** [comment]
Fix below

```css
.ng5-slider-pointer {
  outline: none;
}
```
