### ISSUE TITLE
All CSS overwrites need to be applied with !important

### ISSUE THREAD

**Issue by MickL** [angular-slider/ng5-slider#47]
No matter what style i want to overwrite, i need to add `!important` to it:

**styles.scss**
```
.ng5-slider-pointer {
    background-color: $primary!important;
}
```

**Comment by cmcgroarty** [comment]
have you tried increasing the specificity of your selector?

for example
```html
<ng5-slider class="my-slider"></ng5-slider>
```
```scss
.ng5-slider.my-slider .ng5-slider-pointer {
    background-color: $primary;
}
```
